### ISSUE TITLE
Profile /wp-admin?

### ISSUE THREAD

**Issue by tnorthcutt** [dannyvankooten/wp-plugin-profiler#12]
I haven't dug into the code yet, so not sure if this is possible. It looks like currently, this plugin can't profile admin pages - is that correct? If so, that would be a nice addition for sure.

Great work with it so far, very nice!

**Comment by dannyvankooten** [comment]
Hi @tnorthcutt , 

The requests are fired without any authentication cookies so doing this would not really profile `/wp-admin/`, it would profile the authorisation check and the rendering of the login page.

Great feature suggestion though, will look into adding support for this. :)
